export const SIDO_NAME_DATA = [
  { id: null, value: '지역' },
  { id: '서울', value: '서울' },
  { id: '부산', value: '부산' },
  { id: '대구', value: '대구' },
  { id: '인천', value: '인천' },
  { id: '광주', value: '광주' },
  { id: '대전', value: '대전' },
  { id: '울산', value: '울산' },
  { id: '경기', value: '경기' },
  { id: '강원', value: '강원' },
  { id: '충북', value: '충북' },
  { id: '충남', value: '충남' },
  { id: '전북', value: '전북' },
  { id: '전남', value: '전남' },
  { id: '경북', value: '경북' },
  { id: '경남', value: '경남' },
  { id: '제주', value: '제주' },
  { id: '세종', value: '세종' },
]
